name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEKRS_HOME: ${{ github.workspace }}/.local/nekrs
  NEKRS_INSTALL_DIR: ${{ github.workspace }}/.local/nekrs
  MPICH_FC: gfortran
  NEKRS_EXAMPLES: ${{ github.workspace }}/.local/nekrs/examples
  OCCA_CUDA_ENABLED: 0
  OCCA_HIP_ENABLED: 0
  OCCA_OPENCL_ENABLED: 0
  NEKRS_OCCA_MODE_DEFAULT: SERIAL
  NEKRS_CI: 1

defaults:
  run:
    shell: bash

jobs:

  ethier:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: APT dependencies
      run: |
        sudo apt -y update
        sudo apt install -y mpich libmpich-dev

    - name: install
      run: |
        pwd
        ./nrsconfig
        cmake --build build --target install -j 2

    - name: 'ethier default'
      working-directory: ${{ env.NEKRS_EXAMPLES }}/ethier
      run: ${{ env.NEKRS_HOME }}/bin/nrsmpi ethier 1 1

    - name: 'ethier subcycle'
      working-directory: ${{ env.NEKRS_EXAMPLES }}/ethier
      run: $NEKRS_HOME/bin/nrsmpi ethier 2 2


  lowMach:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: APT dependencies
      run: |
        sudo apt -y update
        sudo apt install -y mpich libmpich-dev

    - name: install
      run: |
        pwd
        ./nrsconfig
        cmake --build build --target install -j 2

    - name: 'lowMach default'
      working-directory: ${{ env.NEKRS_EXAMPLES }}/lowmach
      run: |
        pwd
        $NEKRS_HOME/bin/nrsmpi lowMach 2 1


