name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEKRS_HOME: ${{ github.workspace }}/.local/nekrs
  NEKRS_INSTALL_DIR: ${{ github.workspace }}/.local/nekrs
  MPICH_FC: gfortran
  NEKRS_EXAMPLES: ${{ github.workspace }}/.local/nekrs/examples
  OCCA_CUDA_ENABLED: 0
  OCCA_HIP_ENABLED: 0
  OCCA_OPENCL_ENABLED: 0
  NEKRS_OCCA_MODE_DEFAULT: SERIAL
  NEKRS_CI: 1

defaults:
  run:
    shell: bash

jobs:

  ethier:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ${{ env.NEKRS_EXAMPLES }}/ethier
    steps:

    - uses: actions/checkout@v2

    - name: APT dependencies
      run: |
        sudo apt -y update
        sudo apt install -y mpich libmpich-dev

    - name: install
      working-directory: ${{ github.workspace }}
      run: |
        ./nrsconfig
        cmake --build build --target install -j 2

    - name: 'ethier default'
      run: ${{ env.NEKRS_HOME }}/bin/nrsmpi ethier 1 1

    - name: 'ethier subcycle'
      run: ${{ env.NEKRS_HOME }}/bin/nrsmpi ethier 2 2

    - name: 'ethier velocity and pressure projection'
      run: ${{ env.NEKRS_HOME }}/bin/nrsmpi ethier 2 3

    - name: 'ethier (block) velocity and pressure projection with subcycling'
      run: ${{ env.NEKRS_HOME }}/bin/nrsmpi ethier 2 4

    - name: 'ethier default + moving mesh'
      run: ${{ env.NEKRS_HOME }}/bin/nrsmpi ethier 2 5

    - name: 'ethier subcycle + moving mesh'
      run: ${{ env.NEKRS_HOME }}/bin/nrsmpi ethier 2 6


  lowMach:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ${{ env.NEKRS_EXAMPLES }}/lowMach
    steps:

    - uses: actions/checkout@v2

    - name: APT dependencies
      run: |
        sudo apt -y update
        sudo apt install -y mpich libmpich-dev

    - name: install
      working-directory: ${{ github.workspace }}
      run: |
        ./nrsconfig
        cmake --build build --target install -j 2

    - name: 'lowMach default'
      run: |
        ${{ env.NEKRS_HOME }}/bin/nrsmpi lowMach 2 1

