name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEKRS_HOME: ${{ github.workspace }}/.local/nekrs
  MPICH_FC: gfortran
  NEKRS_EXAMPLES: ${{ github.workspace }}/.local/nekrs/examples
  OCCA_CUDA_ENABLED: 0
  OCCA_HIP_ENABLED: 0
  OCCA_OPENCL_ENABLED: 0
  NEKRS_OCCA_MODE_DEFAULT: SERIAL
  NEKRS_CI: 1

defaults:
  run:
    shell: bash

jobs:

  ethier:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

          #- name: APT dependencies
          #  run: |
          #    sudo apt -y update
          #    sudo apt install -y mpich libmpich-dev

          #- name: install
          #  run: |
          #    pwd
          #    ./nrsconfig
          #    cmake --build build --target install -j 2

    - name: 'ethier default'
      working-directory: ${{ NEK_EXAMPLES }}/ethier
      run: |
        pwd
        $NEKRS_HOME/bin/nrsmpi ethier 1 1

    - name: 'ethier subcycle'
      working-directory: "${NEK_EXAMPLES}/ethier"
      run: |
        pwd
        $NEKRS_HOME/bin/nrsmpi ethier 2 2


  lowMach:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

          #- name: APT dependencies
          #  run: |
          #    sudo apt -y update
          #    sudo apt install -y mpich libmpich-dev

          #- name: install
          #  run: |
          #    pwd
          #    ./nrsconfig
          #    cmake --build build --target install -j 2

    - name: 'lowMach default'
      working-directory: $NEK_EXAMPLES/lowmach
      run: |
        pwd
        $NEKRS_HOME/bin/nrsmpi lowMach 2 1


    

        #main:
        #  runs-on: ubuntu-18.04
        #  strategy: 
        #    matrix:
        #      casename: [ethier, lowMach, mv_cyl]
        #      include:
        #        - casename: ethier
        #          testname: 'ethier default'
        #          tasks: 1
        #          ci_mode: 1

        #        - casename: ethier
        #          testname: 'ethier subcycle'
        #          tasks: 2
        #          ci_mode: 2

        #        - casename: ethier
        #          testname: 'ethier velocity and pressure projection'
        #          tasks: 2
        #          ci_mode: 3

        #        - casename: lowMach
        #          testname: 'lowMach default'
        #          tasks: 2
        #          ci_mode: 1

        #        - casename: mv_cyl
        #          testname: 'mv_cyl'
        #          tasks: 2
        #          ci_mode: 1

        #        - casename: mv_cyl
        #          testname: 'mv_cyl + subcycling'
        #          tasks: 2
        #          ci_mode: 2

        #  steps:

        #    #- name: warm-up
        #    #  shell: bash
        #    #  working-directory: $NEKRS_EXAMPLES
        #    #  run: pwd
      


  # ====== SCRATCH =============
  #  setup:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #
  #      - name: APT Install
  #        shell: bash
  #        run: |
  #          sudo apt -y update
  #          sudo apt install -y mpich libmpich-dev
  #
  #  build_nekrs:
  #    runs-on: ubuntu-latest
  #    needs: setup
  #    steps:
  #
  #      - name: build
  #        shell: bash
  #        run: |
  #          ./nrsconfig
  #          cmake --build build --target install -j 2
  #
  #          # This doesn't work yet...
  #          #- name: archive_build
  #          #  shell: bash
  #          #  uses: actions/upload-artifact@v2
  #          #  with:
  #          #    - name: build_dir
  #          #      path: ${NEKRS_HOME}


#  ethier:
#    runs-on: ubuntu-latest
#    shell: bash
#    needs: build_nekrs
#    steps:
#      - name: download_build_dir
#        uses: actions@download-artifact@v2
#        with:
#          - name: build_dir
#      - name: warmup
#        run: |
#          cd $NEKRS_EXAMPLES/ethier 
#          ${NEKRS_HOME}/bin/nrspre ethier 1
#      - name: default
#        run: |
#          cd $NEKRS_EXAMPLES/ethier 
#          ${NEKRS_HOME}/bin/nrsmpi ethier 1 1
#      - name: subcycle
#        run: |
#          cd $NEKRS_EXAMPLES/ethier 
#          ${NEKRS_HOME}/bin/nrsmpi ethier 2 2
#
#  mv_cyl:
#    runs-on: ubuntu-latest
#    shell: bash
#    needs: build_nekrs
#    steps:
#      - name: download_build_dir
#        uses: actions@download-artifact@v2
#        with:
#          - name: build_dir
#      - name: warmup
#        run: |
#          cd $NEKRS_EXAMPLES/mv_cyl 
#          ${NEKRS_HOME}/bin/nrspre mv_cyl 1
#      - name: default
#        run: |
#          cd $NEKRS_EXAMPLES/mv_cyl 
#          ${NEKRS_HOME}/bin/nrsmpi mv_cyl 2 1
#      - name: subcycle
#        run: |
#          cd $NEKRS_EXAMPLES/mv_cyl 
#          ${NEKRS_HOME}/bin/nrsmpi mv_cyl 2 2
